language: node_js
node_js:
  - "8.15"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - yarn test:check-coverage
after_script:
  - yarn report-coverage
before_install:
  # - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  # - export PATH=$HOME/.yarn/bin:$PATH
  - cd api